### PR TITLE
Bios

### PR DESCRIPTION
**Pull request by andres039**

### CODE REVIEW

**Review by buddhist-uni — APPROVED** [review]
Thanks! For future PRs, it's probably easier to checkout the main `master` branch, then `git checkout -b morebios` to start with a fresh branch.  Cheers!

**Comment by andres039** [comment]
Thanks for the feedback. Just to make sure, do we need a new branch every time there's a pool request? If so, would you like me to delete the branch once is approved?

**Comment by buddhist-uni** [comment]
Yes! That's correct :)

**Comment by andres039** [comment]
Thank you, sounds good.

**Comment by andres039** [comment]
Thank you, sounds good.

**Comment by buddhist-uni** [comment]
No, Thank you! The new bios are now live on the internet 🙂 https://buddhistuniversity.net/authors/bingenheimer

**Pull request merged**
