### PR TITLE
Chapter number update

### PR DESCRIPTION
**Pull request by ColmBhandal**
I think it should be chapter 7, not 6

### CODE REVIEW

**Comment by buddhist-uni** [comment]
Why do you think that? Chapter 6 is on mental development (*bhāvanā*)...

**Comment by ColmBhandal** [comment]
So the link takes me to this website: [Fundamentals of Buddhism](https://www.buddhanet.net/fundbud.htm).

When I look at that I see the chapters laid out as follows:
1. A Modern Perspective
1. Pre-Buddhist Backgound 
1. Life of the Buddha 
1. Four Noble Truths 1 
1. Four Noble Truths 2 
1. Morality 
1. Mental Development 
1. Wisdom 
1. Karma
1. Rebirth
1. Dependent Origination
1. Three Characteristics
1. Five Aggregates
1. Conclusion

Maybe there are different versions of that site and we're talking about different versions? Maybe the latest version updated the chapter numbering e.g. by adding a new chapter and offsetting all subsequent chapters by one?

**Comment by ColmBhandal** [comment]
...Ah! I just realised that there is also a PDF version. So in the PDF version "A Modern Perspective" is not considered as a chapter and all other chapters are therefore one less than they are on the website. I guess that means it's a choice between two evils, and in that case, I suppose the best approach is to just leave things the way they are.

**Comment by buddhist-uni** [comment]
Ah! Okay, thank you. Didn't realize (forgot?) that the website and the PDF have different numbers. 🤔  I can remove the main website link (so there's just that inline PDF link) and then manually add the deep links directly to each chapter in the descriptions. How does that sound?

Thanks for pointing this out!

**Comment by buddhist-uni** [comment]
Ok. Addressed this in 0080c2f. Thanks for the report 🤠

**Pull request closed without merging**
